### ISSUE TITLE
No column called address found in the input file

### ISSUE THREAD

**Issue by siqi-chen** [cole-brokamp/cchmc_batch_geocoder#4]
I have a patient visit data with columns for longitude and latitude values and would like to get the deprivation index using DeGAUSS/cccmc_batch_geocoder. On the geomarker assessment wiki page, it mentions that the geomarker assessment images will also work with a CSV file with columns named “lat” and “lot”. 

My input CSV data with three columns, “id”, “lat” and “lot”, which looks like:

id | lat | lon
-- | -- | --
001 | 39.277826 | -84.566236
002 | 39.15464 | -84.577282
003 | 38.935334 | -84.61042

I ran the command
```
docker run --rm -v "$PWD":/tmp degauss/cchmc_batch_geocoder input.csv
```
and I got an error “No column called address found in the input file”:
```
reading in address file: input.csv...

Parsed with column specification:
cols(
  id = col_character(),
  lat = col_double(),
  lon = col_double()
)
Error: no column called address found in the input file
Execution halted
```

Do I have to include the address column in the input file as well in order to get the deprivation index data? Thanks!

**Comment by cole-brokamp** [comment]
Thanks for the detailed problem explanation.  `cchmc_batch_geocoder` is a little different than the DeGAUSS geomarker assessment containers because it wraps the process of geocoding, census tract assignment, and merging with the deprivation index all into one process.  If you already have geocoded addresses, I would suggest using the census_tracts container to get their census tract identifier and then using that identifier to merge in the deprivation index from https://github.com/cole-brokamp/dep_index/raw/master/ACS_deprivation_index_by_census_tracts.csv

**Comment by siqi-chen** [comment]
Thanks for your suggestion. I tried to run the census_tracts container with the same input using 
```
docker run --rm -v "$PWD":/tmp degauss/census_tracts input.csv
```
but got an error
```
Error: package or namespace load failed for 'tigris':
 .onLoad failed in loadNamespace() for 'sf', details:
  call: get(genname, envir = envir)
  error: object 'group_map' not found
Execution halted
```
Not sure what I need to do to resolve this?

**Comment by cole-brokamp** [comment]
Can you do a `docker pull degauss/census_tracts` so that you have the latest version? This looks like an error that was fixed in an older version.

**Comment by siqi-chen** [comment]
I think I'm using the latest version. Please see below:
```
$ docker pull degauss/census_tracts 
Using default tag: latest
latest: Pulling from degauss/census_tracts
Digest: sha256:469be8eadc6099c0acdd40ebe6c1f0dc87a768d7f8228458964d0671552a7470
Status: Image is up to date for degauss/census_tracts:latest
```

```
$ docker images
REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
degauss/census_tracts           latest              055badd0a4fd        5 weeks ago         1.36GB
degauss/dist_to_major_roadway   latest              7ea0c6774c78        5 weeks ago         1.36GB
degauss/cchmc_batch_geocoder    latest              056abfcea3f1        2 months ago        7.07GB
```

```
$ docker run 055badd0a4fd input.csv 
Error: package or namespace load failed for 'tigris':
 .onLoad failed in loadNamespace() for 'sf', details:
  call: get(genname, envir = envir)
  error: object 'group_map' not found
Execution halted
```

**Comment by cole-brokamp** [comment]
Can you try `degauss/census_tracts:v0.3` and let me know if you see the same problem?

**Comment by siqi-chen** [comment]
`degauss/census_tracts:v0.3` is working properly, thanks!

**Comment by cole-brokamp** [comment]
Thanks for helping me pinpoint the issue!
