### ISSUE TITLE
remove whitespace after removing non-alphanumerics

### ISSUE THREAD

**Issue by erikarasnick** [cole-brokamp/cchmc_batch_geocoder#5]
switch lines of code around to remove whitespace after removing non-alphanumerics

**Comment by cole-brokamp** [comment]
https://github.com/cole-brokamp/cchmc_batch_geocoder/blob/c0ce0c14648f4d4f1f92f1af4668ac9ad33feb52/geocode.R#L23-L30

**Comment by cole-brokamp** [comment]
we don't need to do this as the `usaddress` python module removes more than one whitespace when parsing addresses
